{
 "title": "Resource Utilization Dashboard",
 "tags": [
  "Rancher2",
  "Operations",
  "K8s-Admin"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PromDS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster)"
    }
   },
   {
    "name": "top_network_pods",
    "query": {
     "query": "query_result(topk(10, avg_over_time(container_network_receive_bytes_total{namespace=\"$namespace\",pod!~\"pushprox.*\"}[5m])))"
    }
   },
   {
    "name": "top_memory_pods",
    "query": {
     "query": "query_result(topk(10, avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\"}[5m])))"
    }
   },
   {
    "name": "top_cpu_pods",
    "query": {
     "query": "query_result(topk(10, avg_over_time(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])))"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (avg(irate({__name__=~\"node_cpu_seconds_total|windows_cpu_time_total\",mode=\"idle\"}[5m])))) * 100"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - sum({__name__=~\"node_memory_MemAvailable_bytes|windows_os_physical_memory_free_bytes\"}) / sum({__name__=~\"node_memory_MemTotal_bytes|windows_cs_physical_memory_bytes\"})) * 100"
      }
     ]
    },
    {
     "title": "CPU Requests Commitment",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory Requests Commitment",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "CPU Limits Commitment",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory Limits Commitment",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Level Resource Utilization (All Namespaces)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage by Namespace (All)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(sum by (namespace)(container_memory_working_set_bytes{container!=\"\",namespace!=\"\",container!=\"POD\"}))"
      }
     ]
    },
    {
     "title": "CPU usage by Namespace (All)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (namespace)(irate(container_cpu_usage_seconds_total{container!=\"\",namespace!=\"\",container!=\"POD\"}[5m])))"
      }
     ]
    },
    {
     "title": "ThroughPut(Read+Write) by Namespace (All)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", cluster=\"$cluster\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", namespace!=\"\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "IOPS(Reads+Writes) by Namespace (All)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ceil(sum by(namespace) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", cluster=\"$cluster\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", namespace!=\"\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Inbound Network Traffic by Namespace (All)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace)(rate(container_network_receive_bytes_total{container!=\"\",namespace!=\"\",pod!~\"pushprox.*\"}[5m]))\n"
      }
     ]
    },
    {
     "title": "Outbound Network Traffic by Namespace (All)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace)(rate(container_network_transmit_bytes_total{container!=\"\",namespace!=\"\",pod!~\"pushprox.*\"}[5m]))\n"
      }
     ]
    },
    {
     "title": "Rate of Received Packets Dropped by Namespace (All)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "packets/min" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",pod!~\"pushprox.*\",cluster=\"$cluster\", namespace=~\".+\"}[1m])) by (namespace) * 60\n",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped by Namespace (All)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "packets/min" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[1m])) by (namespace) * 60\n",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Level Resource Utilization ( Namespace: $namespace )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Pods by Memory Usage in '$namespace' Namespace",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (container_memory_working_set_bytes{container!=\"\",namespace=\"$namespace\",pod=~\"$top_memory_pods\",pod_name!=\"POD\"})"
      }
     ]
    },
    {
     "title": "Top Pods by CPU Usage in '$namespace' Namespace",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)(irate(container_cpu_usage_seconds_total{container!=\"\",namespace=\"$namespace\",pod=~\"$top_cpu_pods\"}[5m]))"
      }
     ]
    },
    {
     "title": "Top Pods by ThroughPut(Read+Write) in '$namespace' Namespace",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (\n  rate(container_fs_reads_bytes_total{\n    job=\"kubelet\",\n    metrics_path=\"/metrics/cadvisor\",\n    container!=\"\",\n    device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\",\n    cluster=\"$cluster\",\n    pod!~\"pushprox.*\",\n    namespace=\"$namespace\"}[$__rate_interval]\n  ) + \n  rate(container_fs_writes_bytes_total{\n    job=\"kubelet\",\n    metrics_path=\"/metrics/cadvisor\",\n    container!=\"\",\n    pod!~\"pushprox.*\",\n    cluster=\"$cluster\",\n    namespace=\"$namespace\"}[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top Pods by IOPS(Reads+Writes) in '$namespace' Namespace",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (\n  rate(container_fs_reads_total{\n    job=\"kubelet\",\n    metrics_path=\"/metrics/cadvisor\",\n    container!=\"\",\n    device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\",\n    cluster=\"$cluster\",\n    pod!~\"pushprox.*\",\n    namespace=\"$namespace\"}[$__rate_interval]\n  ) + \n  rate(container_fs_writes_total{\n    job=\"kubelet\",\n    metrics_path=\"/metrics/cadvisor\",\n    container!=\"\",\n    cluster=\"$cluster\",\n    pod!~\"pushprox.*\",\n    namespace=\"$namespace\"}[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top Pods by Inbound Network Traffic in '$namespace' Namespace",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)(rate(container_network_receive_bytes_total{container!=\"\",namespace=\"$namespace\",pod=~\"$top_network_pods\"}[5m]))"
      }
     ]
    },
    {
     "title": "Top Pods by Outbound Network Traffic in '$namespace' Namespace",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)(rate(container_network_transmit_bytes_total{container!=\"\",namespace=\"$namespace\",pod=~\"$top_network_pods\"}[5m]))"
      }
     ]
    },
    {
     "title": "Rate of Received Packets Dropped per pod in $namespace",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "packet/min" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_network_receive_packets_dropped_total{\n    job=\"kubelet\",\n    metrics_path=\"/metrics/cadvisor\",\n    cluster=\"$cluster\",\n    pod!~\"pushprox.*\",\n    namespace=\"$namespace\"}[1m]\n)) * 60\n",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped per pod in $namespace",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "packet/min" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_network_transmit_packets_dropped_total{\n    job=\"kubelet\",\n    metrics_path=\"/metrics/cadvisor\",\n    cluster=\"$cluster\",\n    pod!~\"pushprox.*\",\n    namespace=\"$namespace\"}[1m]\n)) * 60\n",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Level Resource Utilization (pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"$node\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}